### ISSUE TITLE
Notice appear in the login page

### ISSUE THREAD

**Issue by jyou0012** [lzq98/g3-cleaning#1]
XAMPP V3.2.4
Apache/2.4.46 (Win64) OpenSSL/1.1.1j PHP/7.4.16 
When entering the login page from home page, a notice popped out:

Notice: session_start(): A session had already been started - ignoring in C:\xampp\htdocs\g3-cleaning\include\header.php on line 2

![image](https://user-images.githubusercontent.com/81142426/202960720-44a32a36-4529-4531-a758-e472863c87d3.png)

**Comment by lzq98** [comment]
fixed 1344a343cdd75523e9dbb464cd6dc7469c55e437

**Comment by lzq98** [comment]
closed 1344a343cdd75523e9dbb464cd6dc7469c55e437
