### ISSUE TITLE
assets/vendor/php-email-form/validate.js, XSS vulnerability

### ISSUE THREAD

**Issue by HaoyuChen1014** [lzq98/g3-cleaning#4]
Unsanitized input from data from a remote resource flows into innerHTML, Where it is used to dynamically construct the HTML page on client side. This may result in a DOM Based Cross-Site Scripting attack (DOMXSS).
At line 81.

79 function displayError(thisForm, error) {
80     thisForm.querySelector('.loading').classList.remove('d-block');
81     thisForm.querySelector('.error-message').innerHTML = error;

**Comment by lzq98** [comment]
fixed 8b717be710440ed578b782a7aed8546af49be62f
