### ISSUE TITLE
typo in website

### ISSUE THREAD

**Issue by jyou0012** [lzq98/g3-cleaning#6]
Note: Bold text is for typo 
         text after -> are recommanded text

_In **ABOUT US** section:_

- G3 Cleaning was founded in Adelaide in 2022 and is **exbanding** with strong growth. 
- To provide a **geniuine** business opportunity for committed franchisees.
- To protect public health under **Covid**-19 situation. (Covid -> COVID)
- A professionally-trained self-employed house cleaner will strive for excellence every time. -> A professionally-trained,self-employed house cleaner will strive for excellence every time.
- Our vision is to continually offer the best quality home cleaning available in Adelaide SA. By supporting our franchisees to become the best home cleaner they can, we are able to pursue a higher standard of customer service and provide value to our customers every time. -> Our vision is to continually offer the best quality home cleaning available in Adelaide, SA. By supporting our franchisees to become the best home cleaners they can be, we are able to pursue a higher standard of customer service and provide value to our customers every time.

_Under "**We provide our customers with the safest cleaning service**" section_

- We provide our customers with the safest cleaning service -> We provide our customers with the safest cleaning service.
- COVID-19 is now a global pandemic affecting over 200 countries, after its first recorded outbreak in December 2019.  -> COVID-19 is now a global pandemic affecting over 200 countries after its first recorded outbreak in December 2019. 
- Of course you can! G3-Cleaning aims to **provid** our customers with premium quality services and best price. -> with premium-quality services _at the_ best price. 
- Worried of getting infected by **Covid**?
- High quality services at an affordable price! -> High-quality services at a reasonable cost!
- Say goodbye to your weekly cleaning chores, book now. -> Book now and say goodbye to your weekly cleaning chores.
- Moving out has never been easier with our end of lease clean. -> With our end-of-lease cleaning, moving out has never been easier.
- All of our cleaners are insured and Police checked and have certified training.  ->  All of our cleaners are insured, police checked, and have certified training.
- We can return your property to the same standard as when you moved in, 100% satisfaction guaranteed. -> We can restore your property to its original condition, ensuring your complete satisfaction.

_under '**TESTIMONIALS**':_

- G3-**Cleaningaims** to provide the absolute best job possible, on time, every time. 

After done registration:
Your account has been **registed** successfully

**Comment by lzq98** [comment]
fixed 93c58cef08d937aba089e3d50e5cdc46c71edf0a
